font:
  normal:
    # family: Hack Nerd Font Mono
    family: JetBrains Mono Nerd Font
    # family: RobotoMono Nerd Font
    style: Regular

  # bold:
  #   family: Hack Nerd Font Mono
  #   style: Bold

  # italic:
  #   family: Hack Nerd Font Mono
  #   style: Italic

  # bold_italic:
  #   family: Hack Nerd Font Mono
  #   style: Bold Italic

  size: 10

  offset:
    x: 0
    y: 2
